package main

import (
	"fmt"
	"strings"
)

// generateScan generates binding code for scan mode.
// Unlike annotation mode, the generated code imports the scanned package.
func generateScan(b *Bindings) string {
	var w strings.Builder

	// Check if we need []string helpers.
	needsStringSlice := scanNeedsStringSlice(b)

	// Header
	w.WriteString("// Code generated by gluagen. DO NOT EDIT.\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", b.PkgName))

	// Imports
	w.WriteString("import (\n")
	if b.ImportAlias != lastPathComponent(b.ImportPath) {
		w.WriteString(fmt.Sprintf("\t%s %q\n", b.ImportAlias, b.ImportPath))
	} else {
		w.WriteString(fmt.Sprintf("\t%q\n", b.ImportPath))
	}
	w.WriteString("\tlua \"github.com/akzj/go-lua/pkg/lua\"\n")
	w.WriteString(")\n\n")

	// Module opener
	openerName := fmt.Sprintf("LuaOpen_%s", b.ModuleName)
	w.WriteString(fmt.Sprintf("// %s registers the %q module.\n", openerName, b.ModuleName))
	w.WriteString(fmt.Sprintf("func %s(L *lua.State) {\n", openerName))
	w.WriteString(fmt.Sprintf("\tlua.RegisterModule(L, %q, map[string]lua.Function{\n", b.ModuleName))
	for _, f := range b.Funcs {
		w.WriteString(fmt.Sprintf("\t\t%q: lua_%s_%s,\n", f.LuaName, b.ModuleName, f.GoName))
	}
	w.WriteString("\t})\n")
	w.WriteString("}\n\n")

	// Function wrappers
	for _, f := range b.Funcs {
		generateScanFuncWrapper(&w, f, b)
	}

	// Emit []string helpers if needed.
	if needsStringSlice {
		generateStringSliceHelpers(&w)
	}

	return w.String()
}

func generateScanFuncWrapper(w *strings.Builder, f FuncInfo, b *Bindings) {
	funcName := fmt.Sprintf("lua_%s_%s", b.ModuleName, f.GoName)

	w.WriteString(fmt.Sprintf("func %s(L *lua.State) int {\n", funcName))

	// Read parameters from stack.
	paramVarNames := make([]string, len(f.Params))
	for i, p := range f.Params {
		idx := i + 1
		varName := p.Name
		if varName == "" || varName == "_" {
			varName = fmt.Sprintf("arg%d", i+1)
		}
		paramVarNames[i] = varName
		w.WriteString(fmt.Sprintf("\t%s := %s\n", varName, genScanCheckExpr(p, idx)))
	}

	// Build call: pkgAlias.FuncName(args...)
	callExpr := fmt.Sprintf("%s.%s(%s)", b.ImportAlias, f.GoName, strings.Join(paramVarNames, ", "))

	// Handle returns.
	if len(f.Returns) == 0 {
		w.WriteString(fmt.Sprintf("\t%s\n", callExpr))
		w.WriteString("\treturn 0\n")
	} else if f.HasError && len(f.Returns) == 1 {
		w.WriteString(fmt.Sprintf("\terr := %s\n", callExpr))
		w.WriteString("\tif err != nil {\n")
		w.WriteString("\t\tL.PushNil()\n")
		w.WriteString("\t\tL.PushString(err.Error())\n")
		w.WriteString("\t\treturn 2\n")
		w.WriteString("\t}\n")
		w.WriteString("\treturn 0\n")
	} else if f.HasError {
		retNames := genScanReturnNames(f.Returns)
		w.WriteString(fmt.Sprintf("\t%s := %s\n", strings.Join(retNames, ", "), callExpr))
		w.WriteString("\tif err != nil {\n")
		w.WriteString("\t\tL.PushNil()\n")
		w.WriteString("\t\tL.PushString(err.Error())\n")
		w.WriteString("\t\treturn 2\n")
		w.WriteString("\t}\n")
		nPush := 0
		for i, r := range f.Returns {
			if r.IsError {
				continue
			}
			w.WriteString(fmt.Sprintf("\t%s\n", genScanPushExpr(r, retNames[i])))
			nPush++
		}
		w.WriteString(fmt.Sprintf("\treturn %d\n", nPush))
	} else if len(f.Returns) == 1 {
		w.WriteString(fmt.Sprintf("\tresult := %s\n", callExpr))
		w.WriteString(fmt.Sprintf("\t%s\n", genScanPushExpr(f.Returns[0], "result")))
		w.WriteString("\treturn 1\n")
	} else {
		retNames := genScanReturnNames(f.Returns)
		w.WriteString(fmt.Sprintf("\t%s := %s\n", strings.Join(retNames, ", "), callExpr))
		for i, r := range f.Returns {
			w.WriteString(fmt.Sprintf("\t%s\n", genScanPushExpr(r, retNames[i])))
		}
		w.WriteString(fmt.Sprintf("\treturn %d\n", len(f.Returns)))
	}

	w.WriteString("}\n\n")
}

func genScanCheckExpr(p ParamInfo, idx int) string {
	switch p.GoType {
	case "string":
		return fmt.Sprintf("L.CheckString(%d)", idx)
	case "int":
		return fmt.Sprintf("int(L.CheckInteger(%d))", idx)
	case "int8":
		return fmt.Sprintf("int8(L.CheckInteger(%d))", idx)
	case "int16":
		return fmt.Sprintf("int16(L.CheckInteger(%d))", idx)
	case "int32":
		return fmt.Sprintf("int32(L.CheckInteger(%d))", idx)
	case "int64":
		return fmt.Sprintf("L.CheckInteger(%d)", idx)
	case "uint":
		return fmt.Sprintf("uint(L.CheckInteger(%d))", idx)
	case "uint8":
		return fmt.Sprintf("uint8(L.CheckInteger(%d))", idx)
	case "uint16":
		return fmt.Sprintf("uint16(L.CheckInteger(%d))", idx)
	case "uint32":
		return fmt.Sprintf("uint32(L.CheckInteger(%d))", idx)
	case "uint64":
		return fmt.Sprintf("uint64(L.CheckInteger(%d))", idx)
	case "float32":
		return fmt.Sprintf("float32(L.CheckNumber(%d))", idx)
	case "float64":
		return fmt.Sprintf("L.CheckNumber(%d)", idx)
	case "bool":
		return fmt.Sprintf("L.ToBoolean(%d)", idx)
	case "[]byte":
		return fmt.Sprintf("[]byte(L.CheckString(%d))", idx)
	case "[]string":
		return fmt.Sprintf("luaCheckStringSlice(L, %d)", idx)
	default:
		return fmt.Sprintf("L.CheckString(%d) /* unsupported type %s */", idx, p.GoType)
	}
}

func genScanPushExpr(r ReturnInfo, varName string) string {
	switch r.GoType {
	case "string":
		return fmt.Sprintf("L.PushString(%s)", varName)
	case "int":
		return fmt.Sprintf("L.PushInteger(int64(%s))", varName)
	case "int8", "int16", "int32":
		return fmt.Sprintf("L.PushInteger(int64(%s))", varName)
	case "int64":
		return fmt.Sprintf("L.PushInteger(%s)", varName)
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return fmt.Sprintf("L.PushInteger(int64(%s))", varName)
	case "float32":
		return fmt.Sprintf("L.PushNumber(float64(%s))", varName)
	case "float64":
		return fmt.Sprintf("L.PushNumber(%s)", varName)
	case "bool":
		return fmt.Sprintf("L.PushBoolean(%s)", varName)
	case "[]byte":
		return fmt.Sprintf("L.PushString(string(%s))", varName)
	case "[]string":
		return fmt.Sprintf("luaPushStringSlice(L, %s)", varName)
	default:
		return fmt.Sprintf("L.PushString(fmt.Sprint(%s))", varName)
	}
}

func genScanReturnNames(returns []ReturnInfo) []string {
	names := make([]string, len(returns))
	for i, r := range returns {
		if r.IsError {
			names[i] = "err"
		} else {
			names[i] = fmt.Sprintf("r%d", i)
		}
	}
	return names
}

// scanNeedsStringSlice checks if any function uses []string params or returns.
func scanNeedsStringSlice(b *Bindings) bool {
	for _, f := range b.Funcs {
		for _, p := range f.Params {
			if p.GoType == "[]string" {
				return true
			}
		}
		for _, r := range f.Returns {
			if r.GoType == "[]string" {
				return true
			}
		}
	}
	return false
}

// generateStringSliceHelpers emits helper functions for []string ↔ Lua table conversion.
func generateStringSliceHelpers(w *strings.Builder) {
	w.WriteString("func luaCheckStringSlice(L *lua.State, idx int) []string {\n")
	w.WriteString("\tL.CheckType(idx, lua.TypeTable)\n")
	w.WriteString("\tn := L.RawLen(idx)\n")
	w.WriteString("\tresult := make([]string, 0, n)\n")
	w.WriteString("\tfor i := 1; i <= n; i++ {\n")
	w.WriteString("\t\tL.GetI(idx, int64(i))\n")
	w.WriteString("\t\ts, _ := L.ToString(-1)\n")
	w.WriteString("\t\tresult = append(result, s)\n")
	w.WriteString("\t\tL.Pop(1)\n")
	w.WriteString("\t}\n")
	w.WriteString("\treturn result\n")
	w.WriteString("}\n\n")

	w.WriteString("func luaPushStringSlice(L *lua.State, ss []string) {\n")
	w.WriteString("\tL.CreateTable(len(ss), 0)\n")
	w.WriteString("\tfor i, s := range ss {\n")
	w.WriteString("\t\tL.PushString(s)\n")
	w.WriteString("\t\tL.SetI(-2, int64(i+1))\n")
	w.WriteString("\t}\n")
	w.WriteString("}\n\n")
}

// lastPathComponent returns the last component of a path (e.g., "filepath" from "path/filepath").
func lastPathComponent(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[i+1:]
	}
	return path
}
