package main

import (
	"fmt"
	"strings"
)

func generate(b *Bindings) string {
	var w strings.Builder

	// Header
	w.WriteString("// Code generated by gluagen. DO NOT EDIT.\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", b.PkgName))
	w.WriteString("import lua \"github.com/akzj/go-lua/pkg/lua\"\n\n")

	// Module opener function
	openerName := fmt.Sprintf("LuaOpen_%s", b.ModuleName)
	w.WriteString(fmt.Sprintf("// %s registers the %q module.\n", openerName, b.ModuleName))
	w.WriteString(fmt.Sprintf("func %s(L *lua.State) {\n", openerName))

	// Register type metatables
	for _, t := range b.Types {
		mtName := b.ModuleName + "." + t.GoName
		w.WriteString(fmt.Sprintf("\tL.NewMetatable(%q)\n", mtName))
		// If there are fields, use custom __index/__newindex
		if len(t.Fields) > 0 {
			w.WriteString(fmt.Sprintf("\tL.PushFunction(lua_%s__index)\n", t.GoName))
			w.WriteString("\tL.SetField(-2, \"__index\")\n")
			w.WriteString(fmt.Sprintf("\tL.PushFunction(lua_%s__newindex)\n", t.GoName))
			w.WriteString("\tL.SetField(-2, \"__newindex\")\n")
		} else {
			w.WriteString("\tL.PushValue(-1)\n")
			w.WriteString("\tL.SetField(-2, \"__index\")\n") // mt.__index = mt
		}
		// Register methods on metatable
		for _, m := range t.Methods {
			w.WriteString(fmt.Sprintf("\tL.PushFunction(lua_%s_%s)\n", t.GoName, m.GoName))
			w.WriteString(fmt.Sprintf("\tL.SetField(-2, %q)\n", m.LuaName))
		}
		w.WriteString("\tL.Pop(1)\n\n")
	}

	// Register module functions
	w.WriteString(fmt.Sprintf("\tlua.RegisterModule(L, %q, map[string]lua.Function{\n", b.ModuleName))
	for _, f := range b.Funcs {
		w.WriteString(fmt.Sprintf("\t\t%q: lua_%s,\n", f.LuaName, f.GoName))
	}
	w.WriteString("\t})\n")
	w.WriteString("}\n\n")

	// Generate standalone function wrappers
	for _, f := range b.Funcs {
		generateFuncWrapper(&w, f, "")
	}

	// Generate type helpers and method wrappers
	for _, t := range b.Types {
		generateTypeHelpers(&w, t, b.ModuleName)
		for _, m := range t.Methods {
			generateFuncWrapper(&w, m, t.GoName)
		}
		if len(t.Fields) > 0 {
			generateFieldAccessors(&w, t, b.ModuleName)
		}
	}

	return w.String()
}

func generateFuncWrapper(w *strings.Builder, f FuncInfo, typeName string) {
	// Function name: lua_FuncName or lua_Type_Method
	name := "lua_" + f.GoName
	if typeName != "" {
		name = fmt.Sprintf("lua_%s_%s", typeName, f.GoName)
	}

	w.WriteString(fmt.Sprintf("func %s(L *lua.State) int {\n", name))

	// Read receiver (for methods)
	argOffset := 0
	if f.Receiver != "" {
		w.WriteString(fmt.Sprintf("\tself := check%s(L, 1)\n", f.Receiver))
		argOffset = 1
	}

	// Read parameters from stack
	paramVarNames := make([]string, len(f.Params))
	for i, p := range f.Params {
		idx := i + 1 + argOffset
		varName := p.Name
		if varName == "" || varName == "_" {
			varName = fmt.Sprintf("arg%d", i+1)
		}
		paramVarNames[i] = varName
		w.WriteString(fmt.Sprintf("\t%s := %s\n", varName, genCheckExpr(p, idx)))
	}

	// Call the Go function
	callExpr := genCallExpr(f, typeName, paramVarNames)

	if len(f.Returns) == 0 {
		w.WriteString(fmt.Sprintf("\t%s\n", callExpr))
		w.WriteString("\treturn 0\n")
	} else if f.HasError && len(f.Returns) == 1 {
		// Only returns error
		w.WriteString(fmt.Sprintf("\terr := %s\n", callExpr))
		w.WriteString("\tif err != nil {\n")
		w.WriteString("\t\tL.PushNil()\n")
		w.WriteString("\t\tL.PushString(err.Error())\n")
		w.WriteString("\t\treturn 2\n")
		w.WriteString("\t}\n")
		w.WriteString("\treturn 0\n")
	} else if f.HasError {
		// Returns (value..., error)
		retNames := genReturnNames(f.Returns)
		w.WriteString(fmt.Sprintf("\t%s := %s\n", retNames, callExpr))
		errName := fmt.Sprintf("retErr")
		w.WriteString(fmt.Sprintf("\tif %s != nil {\n", errName))
		w.WriteString("\t\tL.PushNil()\n")
		w.WriteString(fmt.Sprintf("\t\tL.PushString(%s.Error())\n", errName))
		w.WriteString("\t\treturn 2\n")
		w.WriteString("\t}\n")
		// Push non-error returns
		nPush := 0
		for i, r := range f.Returns {
			if !r.IsError {
				w.WriteString(fmt.Sprintf("\t%s\n", genPushExpr(r, fmt.Sprintf("ret%d", i))))
				nPush++
			}
		}
		w.WriteString(fmt.Sprintf("\treturn %d\n", nPush))
	} else {
		// Returns values only
		if len(f.Returns) == 1 {
			w.WriteString(fmt.Sprintf("\tresult := %s\n", callExpr))
			w.WriteString(fmt.Sprintf("\t%s\n", genPushExpr(f.Returns[0], "result")))
			w.WriteString("\treturn 1\n")
		} else {
			retNames := genReturnNames(f.Returns)
			w.WriteString(fmt.Sprintf("\t%s := %s\n", retNames, callExpr))
			for i, r := range f.Returns {
				w.WriteString(fmt.Sprintf("\t%s\n", genPushExpr(r, fmt.Sprintf("ret%d", i))))
			}
			w.WriteString(fmt.Sprintf("\treturn %d\n", len(f.Returns)))
		}
	}

	w.WriteString("}\n\n")
}

// genCheckExpr generates the expression to read a parameter from the Lua stack.
func genCheckExpr(p ParamInfo, idx int) string {
	switch p.GoType {
	case "string":
		return fmt.Sprintf("L.CheckString(%d)", idx)
	case "int":
		return fmt.Sprintf("int(L.CheckInteger(%d))", idx)
	case "int8":
		return fmt.Sprintf("int8(L.CheckInteger(%d))", idx)
	case "int16":
		return fmt.Sprintf("int16(L.CheckInteger(%d))", idx)
	case "int32":
		return fmt.Sprintf("int32(L.CheckInteger(%d))", idx)
	case "int64":
		return fmt.Sprintf("L.CheckInteger(%d)", idx)
	case "uint":
		return fmt.Sprintf("uint(L.CheckInteger(%d))", idx)
	case "uint8":
		return fmt.Sprintf("uint8(L.CheckInteger(%d))", idx)
	case "uint16":
		return fmt.Sprintf("uint16(L.CheckInteger(%d))", idx)
	case "uint32":
		return fmt.Sprintf("uint32(L.CheckInteger(%d))", idx)
	case "uint64":
		return fmt.Sprintf("uint64(L.CheckInteger(%d))", idx)
	case "float32":
		return fmt.Sprintf("float32(L.CheckNumber(%d))", idx)
	case "float64":
		return fmt.Sprintf("L.CheckNumber(%d)", idx)
	case "bool":
		return fmt.Sprintf("L.ToBoolean(%d)", idx)
	default:
		if p.IsPtr {
			// Pointer to struct — use checkXxx helper
			typeName := strings.TrimPrefix(p.GoType, "*")
			return fmt.Sprintf("check%s(L, %d)", typeName, idx)
		}
		// Unknown type — use userdata with type assertion
		return fmt.Sprintf("L.CheckUserdata(%d).(%s)", idx, p.GoType)
	}
}

// genPushExpr generates the expression to push a return value onto the Lua stack.
func genPushExpr(r ReturnInfo, varName string) string {
	switch r.GoType {
	case "string":
		return fmt.Sprintf("L.PushString(%s)", varName)
	case "int":
		return fmt.Sprintf("L.PushInteger(int64(%s))", varName)
	case "int8", "int16", "int32":
		return fmt.Sprintf("L.PushInteger(int64(%s))", varName)
	case "int64":
		return fmt.Sprintf("L.PushInteger(%s)", varName)
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return fmt.Sprintf("L.PushInteger(int64(%s))", varName)
	case "float32":
		return fmt.Sprintf("L.PushNumber(float64(%s))", varName)
	case "float64":
		return fmt.Sprintf("L.PushNumber(%s)", varName)
	case "bool":
		return fmt.Sprintf("L.PushBoolean(%s)", varName)
	default:
		if r.IsPtr {
			typeName := strings.TrimPrefix(r.GoType, "*")
			return fmt.Sprintf("push%s(L, %s)", typeName, varName)
		}
		return fmt.Sprintf("L.PushAny(%s)", varName)
	}
}

// genCallExpr generates the Go function call expression.
func genCallExpr(f FuncInfo, typeName string, paramVarNames []string) string {
	args := strings.Join(paramVarNames, ", ")
	if f.Receiver != "" {
		return fmt.Sprintf("self.%s(%s)", f.GoName, args)
	}
	return fmt.Sprintf("%s(%s)", f.GoName, args)
}

// genReturnNames generates the return variable names like "ret0, ret1, retErr".
func genReturnNames(returns []ReturnInfo) string {
	names := make([]string, len(returns))
	for i, r := range returns {
		if r.IsError {
			names[i] = "retErr"
		} else {
			names[i] = fmt.Sprintf("ret%d", i)
		}
	}
	return strings.Join(names, ", ")
}
