package main

import (
	"strings"
	"testing"
)

func TestParseAndGenerate(t *testing.T) {
	pkg, err := parsePackage("testdata/example")
	if err != nil {
		t.Fatal(err)
	}

	bindings := collectBindings(pkg)

	// Check module name
	if bindings.ModuleName != "game" {
		t.Errorf("expected module name 'game', got %q", bindings.ModuleName)
	}

	// Check types
	if len(bindings.Types) != 1 {
		t.Fatalf("expected 1 type, got %d", len(bindings.Types))
	}
	if bindings.Types[0].GoName != "Player" {
		t.Errorf("expected type Player, got %s", bindings.Types[0].GoName)
	}
	if len(bindings.Types[0].Fields) != 3 {
		t.Errorf("expected 3 fields, got %d", len(bindings.Types[0].Fields))
	}

	// Check standalone functions
	if len(bindings.Funcs) != 2 { // NewPlayer + CalculateDamage
		t.Errorf("expected 2 standalone funcs, got %d", len(bindings.Funcs))
	}

	// Check methods
	if len(bindings.Types[0].Methods) != 3 { // Attack, Heal, String
		t.Errorf("expected 3 methods, got %d", len(bindings.Types[0].Methods))
	}

	// Generate code
	code := generate(bindings)

	// Basic checks on generated code
	if !strings.Contains(code, "Code generated by gluagen") {
		t.Error("missing generated header")
	}
	if !strings.Contains(code, "LuaOpen_game") {
		t.Error("missing LuaOpen_game function")
	}
	if !strings.Contains(code, "lua_NewPlayer") {
		t.Error("missing lua_NewPlayer function")
	}
	if !strings.Contains(code, "lua_Player_Attack") {
		t.Error("missing lua_Player_Attack method wrapper")
	}
	if !strings.Contains(code, "pushPlayer") {
		t.Error("missing pushPlayer helper")
	}
	if !strings.Contains(code, "checkPlayer") {
		t.Error("missing checkPlayer helper")
	}
	if !strings.Contains(code, "lua_Player__index") {
		t.Error("missing __index accessor")
	}
	if !strings.Contains(code, `"game.Player"`) {
		t.Error("missing metatable name")
	}

	t.Logf("Generated code:\n%s", code)
}

func TestToSnakeCase(t *testing.T) {
	tests := []struct{ in, want string }{
		{"NewPlayer", "new_player"},
		{"CalculateDamage", "calculate_damage"},
		{"HP", "hp"},
		{"GetHP", "get_hp"},
		{"HTTPClient", "http_client"},
		{"Attack", "attack"},
	}
	for _, tt := range tests {
		got := toSnakeCase(tt.in)
		if got != tt.want {
			t.Errorf("toSnakeCase(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}
